### ISSUE TITLE
Mk2 - Led 7 always on

### ISSUE THREAD

**Issue by Madsiboy1995** [TomWhitwell/Turing-Pulse-Expander#3]
Hey Tom
Thanks for some great modules. Just finished building Turing Machine + Pulses MK2. 
Unfortunately LED #7 is continuous and not pulsing like the rest. 

Is there an explanation for this?

Best regards

**Comment by TomWhitwell** [comment]
Hi, that must be annoying. This isn’t a problem I’ve heard of before. 

A few ideas about how to approach it. 

As an experiment, try temporarily connecting the pulses to the other (gate) output on the back of the Turing. You’ll see the lights stay on for the whole step length (rather than blinking with the clock). 

If LED 7 is flashing on and off with the others, the problem is in the Turing module. If it is permanently on, the problem is probably in the expander. 

If the problem is in the expander - that’s good, because it’s a very simple module. 

Are the LEDs on the right working as you’d expect? Does step 7 output a changing pulse, or is if always on?

**Comment by Madsiboy1995** [comment]
Wow Tom! So fast response.

I've tried changing out the resistors, but in the end it turned out it was a small shortage at the chip.
Eveything is working now!

**Comment by Suuupedepoissooon** [comment]
Hello everybody !

I am experiencing the same issue, but with the "4+7" LED -> the LED is always on and no pulse is getting out of the step.
I tryed the other output of the turing machine and there is no difference, so the problem seems to be with the expender.
I double checked the chip but it seems I don't have the same issue as Madsiboy. I also replaced the two resistances related to the step but nothing changed.

Any idea ? Best regards
